src/apps/movimientos/urls.py
from django.urls import path
from .views import (
   Transferencia,
   HistorialMovimientos,
   IngresoDinero,
   TransferenciaCuenta,
   MovimientoDetailView,
   # HistorialMovimientosAdmin
)

app_name = "movimientos"

urlpatterns = [
    path("historial/", HistorialMovimientos.as_view(), name="historial"),
    path('transferencia/', Transferencia.as_view(), name='transferencia'),
    path("ingreso_dinero/", IngresoDinero.as_view(), name="ingreso_dinero"),
    path('transferencia_cuenta/<int:cuenta_asociada_id>/', TransferenciaCuenta.as_view(), name='transferencia_cuenta'),
    path('movimiento_detail/<int:pk>/', MovimientoDetailView.as_view(), name='movimiento_detail'),
    # path("admin_historial/", HistorialMovimientosAdmin.as_view(), name="admin_historial"),
]

src/config/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

from . import views

# Vistas de apps.usuarios que quiero que tenga path desde de la raiz
from apps.usuarios import views as usuarios_views
from apps.movimientos import views as movimientos_views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('panel', usuarios_views.UsuarioPanelView.as_view(), name='panel'),
    path('perfil', usuarios_views.UsuarioUpdateProfileView.as_view(), name='profile'),
    path('registro', usuarios_views.UsuarioRegistroView.as_view(), name='register'),
    path('login', usuarios_views.UsuarioLoginView.as_view(), name='login'),
    path('logout', usuarios_views.UsuarioLogoutView.as_view(), name='logout'),
    # Reset password
    path('resetear-password/', usuarios_views.UsuarioResetearPasswordView.as_view(), name='password_reset'),
    path('resetear-password/done', usuarios_views.UsuarioResetearPasswordDoneView.as_view(), name='password_reset_done'),
    path('resetear-password/confirm/<uidb64>/<token>/', usuarios_views.UsuarioResetearPasswordConfirmView.as_view(), name='password_reset_confirm'),
    path('resetear-password/complete', usuarios_views.UsuarioResetearPasswordCompleteView.as_view(), name='password_reset_complete'),
    # Fin reset password
    path('cambiar-password/', usuarios_views.UsuarioCambiarPasswordView.as_view(), name='cambiar-password'),
    path('administracion/transferencia_motivo/', include('apps.transferencia_motivo.urls')),
    path('administracion/usuarios/', include('apps.usuarios.urls')),
    path("administracion/movimientos", movimientos_views.HistorialMovimientosAdmin.as_view(), name="admin_historial"),
    path('movimientos/', include('apps.movimientos.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/apps/movimientos/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.db.models import Count
from apps.transferencia_motivo.models import MotivoTransferencia
import django_filters
from django.forms import TextInput, Select, DateInput

class MovimientoManager(models.Manager):
    def cuentas_mas_utilizadas(self, usuario, limite=10):
        return (
            self.get_queryset()
            .filter(cuenta=usuario)  # Filtra por el usuario logueado
            .values('cuenta_asociada', 'cuenta_asociada__username')  # Agrupa por la cuenta asociada
            .annotate(total=Count('cuenta_asociada'))  # Cuenta la cantidad de movimientos por cuenta asociada
            .order_by('-total')[:limite] # Ordenar por cantidad de uso
        )
class Movimiento(models.Model):
    TIPO_CHOICES = [
        (1, "Ingreso de dinero"),
        (2, "Transferencia enviada"),
        (3, "Transferencia recibida"),
    ]

    tipo = models.PositiveSmallIntegerField(choices=TIPO_CHOICES)
    cuenta = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="movimientos")
    cuenta_asociada = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name="movimientos_asociados"
    )
    transferencia_motivo = models.ForeignKey("transferencia_motivo.MotivoTransferencia", on_delete=models.SET_NULL, null=True, blank=True)
    monto = models.DecimalField(max_digits=10, decimal_places=2)
    fecha = models.DateTimeField(auto_now_add=True)

    objects = MovimientoManager()

    def __str__(self):
        return f"{self.get_tipo_display()} - {self.monto} ({self.fecha})"
    
    def save(self, *args, **kwargs):
        # Modificar un parámetro antes de guardar
         if self.tipo == 2:
            self.cuenta =  self.cuenta * -1
         if self.tipo == 4:
            self.monto =  self.monto * -1
         super().save(*args, **kwargs)

class MovimientoFilter(django_filters.FilterSet):
    fecha = django_filters.DateFromToRangeFilter(
        field_name='fecha',
        label="Rango de Fechas",
        widget=django_filters.widgets.RangeWidget(  # Define RangeWidget aquí
            attrs={
                'class': 'form-control form-control-sm', 
                'type': 'date'  # Selector de fechas HTML5
            }
        )
    )
    cuenta_asociada = django_filters.CharFilter(
        field_name='cuenta_asociada__username',
        lookup_expr='icontains',
        label="Cuenta Asociada",
        widget=TextInput(attrs={'class': 'form-control form-control-sm'})
    )
    tipo = django_filters.ChoiceFilter(
        choices=Movimiento.TIPO_CHOICES,
        label="Tipo",
        widget=Select(attrs={'class': 'form-select form-select-sm'})
    )
    monto = django_filters.RangeFilter(
        field_name='monto',
        label="Rango de Monto",
        widget=django_filters.widgets.RangeWidget(
            attrs={'class': 'form-control form-control-sm', 'placeholder': 'Monto'}
        )
    )
    transferencia_motivo = django_filters.ModelChoiceFilter(
        queryset=MotivoTransferencia.objects.all(),  # Opciones dinámicas desde el modelo relacionado
        label="Motivo de Transferencia",
        widget=Select(attrs={'class': 'form-select form-select-sm'})
    )

    class Meta:
        model = Movimiento
        fields = ['fecha', 'cuenta_asociada', 'tipo', 'monto', 'transferencia_motivo']

#models y filters para admin
class MovimientoAdmin(models.Model):
    TIPO_CHOICES = [
        (1, "Ingreso de dinero"),
        (2, "Transferencia enviada"),
        (3, "Transferencia recibida"),
    ]

    tipo = models.PositiveSmallIntegerField(choices=TIPO_CHOICES)
    cuenta = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="admin_movimientos")
    cuenta_asociada = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name="admin_movimientos_asociados"
    )
    transferencia_motivo = models.ForeignKey("transferencia_motivo.MotivoTransferencia", on_delete=models.SET_NULL, null=True, blank=True)
    monto = models.DecimalField(max_digits=10, decimal_places=2)
    fecha = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.get_tipo_display()} - {self.monto} ({self.fecha})"

class MovimientoAdminFilter(django_filters.FilterSet):
    fecha = django_filters.DateFromToRangeFilter(
        field_name='fecha',
        label="Rango de Fechas",
        widget=django_filters.widgets.RangeWidget(  # Define RangeWidget aquí
            attrs={
                'class': 'form-control form-control-sm', 
                'type': 'date'  # Selector de fechas HTML5
            }
        )
    )

    cuenta = django_filters.CharFilter(
        field_name='cuenta__username',
        lookup_expr='icontains',
        label="Cuenta Origen",
        widget=TextInput(attrs={'class': 'form-control form-control-sm'})
    )

    cuenta_asociada = django_filters.CharFilter(
        field_name='cuenta_asociada__username',
        lookup_expr='icontains',
        label="Cuenta Destino",
        widget=TextInput(attrs={'class': 'form-control form-control-sm'})
    )
     
    tipo = django_filters.ChoiceFilter(
        choices=MovimientoAdmin.TIPO_CHOICES,
        label="Tipo",
        widget=Select(attrs={'class': 'form-select form-select-sm'})
    )
    monto = django_filters.RangeFilter(
        field_name='monto',
        label="Rango de Monto",
        widget=django_filters.widgets.RangeWidget(
            attrs={'class': 'form-control form-control-sm', 'placeholder': 'Monto'}
        )
    )
    transferencia_motivo = django_filters.ModelChoiceFilter(
        queryset=MotivoTransferencia.objects.all(),  # Opciones dinámicas desde el modelo relacionado
        label="Motivo de Transferencia",
        widget=Select(attrs={'class': 'form-select form-select-sm'})
    )

    class Meta:
        model = MovimientoAdmin
        fields = ['fecha',  'cuenta', 'cuenta_asociada', 'tipo', 'monto', 'transferencia_motivo']

    

src/apps/movimientos/forms.py
from django import forms
from .models import Movimiento
from apps.transferencia_motivo.models import MotivoTransferencia
from apps.usuarios.models import Usuario

class MovimientoForm(forms.ModelForm):
    class Meta:
        model = Movimiento
        fields = ["tipo", "cuenta", "cuenta_asociada", "monto", "transferencia_motivo"]


class TransferenciaForm(forms.Form):
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)  # Extrae el usuario de los kwargs
        super().__init__(*args, **kwargs)

        # Filtra el queryset de 'cuenta_asociada_id' para excluir al usuario actual
        if user:
            self.fields['cuenta_asociada_id'].queryset = Usuario.objects.exclude(id=user.id)
    cuenta_asociada_id = forms.ModelChoiceField(
        queryset=Usuario.objects.all(),
        label="Selecciona la cuenta destino:",
        required=True,
    )
    monto = forms.DecimalField(
        label="Monto:",
        max_digits=10,
        decimal_places=2,
        min_value=10,
        required=True
    )
    transferencia_motivo = forms.ModelChoiceField(
        queryset=MotivoTransferencia.objects.all(),
        required=True,
        label="Selecciona el motivo de la transferencia:"
    )
class IngresoDineroForm(forms.Form):
    monto = forms.DecimalField(
        label="Monto a ingresar:",
        max_digits=10,
        decimal_places=2,
        min_value=0.01,
        required=True,
        widget=forms.NumberInput(attrs={"class": "form-control", "placeholder": "Ingrese el monto"})
    )

class TransferenciaCuentaForm(forms.Form):
    def __init__(self, *args, **kwargs):
        cuenta_asociada_id = kwargs.pop('cuenta_asociada_id', None)
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

        if cuenta_asociada_id:
            self.fields['cuenta_asociada_id'].initial = cuenta_asociada_id
            self.fields['cuenta_asociada_id'].queryset = Usuario.objects.filter(id=cuenta_asociada_id)

    cuenta_asociada_id = forms.ModelChoiceField(
        queryset=Usuario.objects.all(),
        label="Selecciona la cuenta destino:",
        required=True,
    )
    monto = forms.DecimalField(
        label="Monto:",
        max_digits=10,
        decimal_places=2,
        min_value=10,
        required=True
    )
    transferencia_motivo = forms.ModelChoiceField(
        queryset=MotivoTransferencia.objects.all(),
        required=True,
        label="Selecciona el motivo de la transferencia:"
    )

src/apps/movimientos/views.py
from django.shortcuts import redirect
from django.views.generic import ListView
from apps.transferencia_motivo.models import MotivoTransferencia
from apps.usuarios.models import Usuario
from .models import Movimiento, MovimientoFilter, MovimientoAdmin, MovimientoAdminFilter
from .forms import IngresoDineroForm, TransferenciaCuentaForm
from django.shortcuts import get_object_or_404
from django.db import transaction
from django.contrib import messages
from .forms import TransferenciaForm 
from django.http import HttpResponseRedirect
from django.views.generic import FormView
from django.urls import reverse
from django.views.generic.detail import DetailView
from django_filters.views import FilterView

from config.mixins import TestStaffMixin

class HistorialMovimientos(FilterView):
    model = Movimiento
    template_name = "movimientos/mi_historial_movimientos.html"
    context_object_name = "movimientos"
    paginate_by = 10 # Número de elementos por página
    filterset_class = MovimientoFilter

    def get_queryset(self):
        # Filtrar movimientos por el usuario logueado
        return Movimiento.objects.filter(cuenta=self.request.user.id).order_by("-fecha")

    def get_context_data(self, **kwargs):
        # Agregar datos adicionales al contexto
        context = super().get_context_data(**kwargs)
        context["total_paginas"] = context["paginator"].num_pages
        context["monto_total"] = self.request.user.saldo  
        return context

class HistorialMovimientosAdmin(TestStaffMixin, FilterView):
    model = MovimientoAdmin
    template_name = "movimientos/admin_historial_movimientos.html"
    context_object_name = "movimientos"
    paginate_by = 10 # Número de elementos por página
    filterset_class = MovimientoAdminFilter

    def get_queryset(self):
        return Movimiento.objects.all().order_by("-fecha")

class Transferencia(FormView):
    template_name = 'movimientos/transferencia.html'
    form_class = TransferenciaForm

    def form_valid(self, form):
 
        cuenta_asociada_id = form.cleaned_data['cuenta_asociada_id']
        print(cuenta_asociada_id) # 
       
        monto = form.cleaned_data['monto']
        transferencia_motivo = form.cleaned_data['transferencia_motivo']

        # Obtener el usuario origen (el usuario logueado)
        usuario_origen = get_object_or_404(Usuario, pk=self.request.user.id)
        usuario_destino = get_object_or_404(Usuario, pk=cuenta_asociada_id.id)

        #mostrar en consola usuarios
        print("Usuario origen:", usuario_origen)
        print("Usuario destino:", usuario_destino)

        # Verificar si hay suficiente saldo
        if usuario_origen.saldo < monto:
            messages.error(self.request, "Saldo insuficiente.")
            return self.form_invalid(form)

        try:
            with transaction.atomic():
                # Actualizar saldos
                usuario_origen.saldo -= monto
                usuario_origen.save()

                usuario_destino.saldo += monto
                usuario_destino.save()

                # Registrar movimientos
                Movimiento.objects.create(
                    cuenta=usuario_origen,  # Emisor
                    cuenta_asociada=usuario_destino,  # Receptor
                    tipo='2',  # Transferencia realizada
                    monto=monto,
                    transferencia_motivo=transferencia_motivo,
                )

                Movimiento.objects.create(
                    cuenta=usuario_destino,  # Receptor
                    cuenta_asociada=usuario_origen,  # Emisor
                    tipo='3',  # Transferencia recibida
                    monto=monto,
                    transferencia_motivo=transferencia_motivo,
                )

            messages.success(self.request, "Transferencia realizada con éxito.")
            return HttpResponseRedirect(reverse('panel'))

        except Exception as e:
            messages.error(self.request, f"Error al realizar la transferencia: {str(e)}")
            return self.form_invalid(form)

    def form_invalid(self, form):
        # Esta función maneja lo que ocurre si el formulario es inválido
        motivos = MotivoTransferencia.objects.all()  
        usuarios = Usuario.objects.exclude(id=self.request.user.id)
        return self.render_to_response(self.get_context_data(form=form, usuarios=usuarios, motivos=motivos))

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

class TransferenciaCuenta(FormView):
    template_name = 'movimientos/transferencia_cuenta.html'
    form_class = TransferenciaCuentaForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        cuenta_id = self.kwargs.get('cuenta_asociada_id')
        kwargs['cuenta_asociada_id'] = cuenta_id  
        kwargs['user'] = self.request.user  
        return kwargs

class IngresoDinero(FormView):
    template_name = "movimientos/ingreso_dinero.html"
    form_class = IngresoDineroForm

    def form_valid(self, form):
        monto = form.cleaned_data["monto"]
        usuario = self.request.user  # Usuario logueado

        try:
            with transaction.atomic():
                usuario.saldo += monto
                usuario.save()

                Movimiento.objects.create(
                    cuenta=usuario,
                    cuenta_asociada=None,
                    tipo="1",
                    monto=monto,
                )

            messages.success(self.request, f"Se han ingresado ${monto:.2f} a tu cuenta.")
        except Exception as e:
            messages.error(self.request, f"Error al realizar el ingreso: {str(e)}")

        return redirect("panel")

    def form_invalid(self, form):
        messages.error(self.request, "Por favor corrige los errores del formulario.")
        return super().form_invalid(form)

class MovimientoDetailView(DetailView):
    model = Movimiento
    template_name = 'movimientos/movimiento_detail.html'
    context_object_name = 'movimiento'

src/templates/movimientos/_filtro_mi_historial.html
{% load django_bootstrap5 %}
<form method="get" class="mb-3 border border-secondary rounded p-3 bg-body-tertiary">
    <div class="row">
        {% for field in filter.form %}
        <div class="col-md-4">
            {% bootstrap_field field %}
        </div>
    {% endfor %}    
    </div>
    <div class="d-flex justify-content-end mt-2">
        <button type="submit" class="btn btn-primary btn-sm me-2">Filtrar</button>
        {% if request.META.HTTP_REFERER and 'admin' in request.META.HTTP_REFERER %}
        <a href="{% url 'admin_historial' %}" class="btn btn-secondary btn-sm">Limpiar</a>
        {% else %}
        <a href="{% url 'movimientos:historial' %}" class="btn btn-secondary btn-sm">Limpiar</a>
        {% endif %}
    </div>
</form>

src/templates/movimientos/admin_historial_movimientos.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block block_name %}Historial de movimientos{% endblock %}
{% block content %}
    <h1>Historial de movimientos</h1>
 <!-- Formulario de Filtros -->
{% include 'movimientos/_filtro_mi_historial.html' %}

{% if movimientos %}
    
<div class="table-responsive">
    <table class="table table-striped table-hover table-bordered align-middle"> 
        <thead class="table-dark">
            <tr>
                <th class="text-center">Fecha Hora</th>
                <th class="text-center">Tipo</th>
                <th class="text-center">Monto</th>
                <th class="text-center">Cuenta Origen</th>
                <th class="text-center">Cuenta Destino</th>
                <th class="text-center">Motivo Transferencia</th>
                <th class="text-center">Comprobante</th>
            </tr>
        </thead>
        <tbody>
            {% for movimiento in movimientos %}
            <tr>
                <td class="text-center text-nowrap">{{ movimiento.fecha|date:"d/m/Y H:i" }}</td>
                <td>{{ movimiento.get_tipo_display }}</td>
                <td class="text-end {% if movimiento.get_tipo_display == 'Transferencia enviada' %}text-danger {% else %} text-success {% endif %}">
                    {% if movimiento.get_tipo_display == 'Transferencia enviada' %} - {% endif %}{{ movimiento.monto }}
                </td>
                <td class="text-center text-nowrap">
                    {{ movimiento.cuenta.username }}
                </td>
                <td class="text-center text-nowrap">
                    {% if movimiento.cuenta_asociada %}
                        {{ movimiento.cuenta_asociada.username }}
                    {% else %}
                        N/A
                    {% endif %}
                </td>
                <td class="text-center text-nowrap">
                    {% if movimiento.transferencia_motivo %}
                        {{ movimiento.transferencia_motivo }}
                    {% else %}
                        N/A
                    {% endif %}
                </td>
                <td class="text-center">
                    <a class="btn btn-link text-decoration-none" href="{% url 'movimientos:movimiento_detail' movimiento.id %}">
                        <i class="fa-solid fa-file-lines fa-lg"></i>
                    </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% include '_filter_pagination.html' %}

{% if movimientos.count == 0 %}
<div class="alert alert-warning text-center" role="alert">
    No existen movimientos registrados.
</div>
{% endif %}

{% endif %}

{% endblock %}

src/templates/movimientos/crear_movimiento.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
<div class="container mt-5">
    <h1 class="text-center mb-4">Crear Movimiento</h1>
    <form method="post" class="border border-secondary rounded p-4 shadow-sm">
        {% csrf_token %}
        
        <div class="mb-3">
            {{ form.as_p }}
        </div>
        
        <button type="submit" class="btn btn-primary w-100">Guardar</button>
    </form>
</div>
</html>
{% endblock %}

src/templates/movimientos/cuentas_favoritas.html
{% if cuentas %}
    <div class="table-responsive">
        <table class="table table-striped table-hover table-bordered align-middle"> 
            <thead class="table-dark">
        <thead>
            <tr>
                <th class="text-center">Cuenta</th>
                <th class="text-center">Cantidad de Transferencias</th>
                <th class="text-center">Acción</th>
            </tr>
        </thead>
        <tbody>
            {% for cuenta in cuentas %}
            {% if cuenta.cuenta_asociada__username != None %}
            <tr>
                <td>{{ cuenta.cuenta_asociada__username}}</td>
                <td class="text-end">{{ cuenta.total }}</td>
                <td class="text-center">
                    <a href="{% url 'movimientos:transferencia_cuenta' cuenta.cuenta_asociada %}" class="btn btn-success btn-sm" data-bs-toggle="tooltip" data-bs-title="Ingrese dinero">
                        <i class="fa-solid fa-money-bill-transfer fa-lg"></i>
                    </a>
                </td>
            </tr>
            {% endif %}
            {% endfor %}
        </tbody>
    </table>
</div>
{% else %}
    <p class="mb-0 fst-italic text-secondary fw-bold">Sin cuentas favoritas.</p>
{% endif %}

src/templates/movimientos/ingreso_dinero.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
    <div class="container mt-5">
        <h1 class="text-center mb-4">Ingresar Dinero</h1>
        
        {% bootstrap_messages %}
        
        <form method="post" action="{% url 'movimientos:ingreso_dinero' %}">
            {% csrf_token %}

            {% bootstrap_form form %}
            
            <button type="submit" class="btn btn-primary w-100">Ingresar</button>
        </form>
    </div>
{% endblock %}

src/templates/movimientos/mi_historial_movimientos.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
    <h1>Mi historial de transacciones</h1>
    <h3 class="text-end text-info" style="margin-bottom: 15px;">
        <i class="fa-solid fa-sack-dollar me-1 text-warning"></i> Saldo Actual: ($) {{ monto_total }}
    </h3>
 <!-- Formulario de Filtros -->
  {% include 'movimientos/_filtro_mi_historial.html' %}

    {% if movimientos %}
<div class="table-responsive">
    <table class="table table-striped table-hover table-bordered align-middle"> 
        <thead class="table-dark">
            <tr>
                <th class="text-center">Fecha Hora</th>
                <th class="text-center">Tipo</th>
                <th class="text-center">Monto</th>
                <th class="text-center">Cuenta Asociada</th>
                <th class="text-center">Motivo Transferencia</th>
                <th class="text-center">Comprobante</th>
            </tr>
        </thead>
        <tbody>
            {% for movimiento in movimientos %}
            <tr>
                <td class="text-center text-nowrap">{{ movimiento.fecha|date:"d/m/Y H:i" }}</td>
                <td>{{ movimiento.get_tipo_display }}</td>
                <td class="text-end {% if movimiento.get_tipo_display == 'Transferencia enviada' %}text-danger {% else %} text-success {% endif %}">
                    {% if movimiento.get_tipo_display == 'Transferencia enviada' %} - {% endif %}{{ movimiento.monto }}
                </td>
                <td class="text-center text-nowrap">
                    {% if movimiento.cuenta_asociada %}
                        {{ movimiento.cuenta_asociada.username }}
                    {% else %}
                        N/A
                    {% endif %}
                </td>
                <td class="text-center text-nowrap">
                    {% if movimiento.transferencia_motivo %}
                        {{ movimiento.transferencia_motivo }}
                    {% else %}
                        N/A
                    {% endif %}
                </td>
                <td class="text-center">
                    <a class="btn btn-link text-decoration-none" href="{% url 'movimientos:movimiento_detail' movimiento.id %}">
                        <i class="fa-solid fa-file-lines fa-lg"></i>
                    </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% include '_filter_pagination.html' %}
{% if movimientos.count == 0 %}
<div class="alert alert-warning text-center" role="alert">
    No existen movimientos registrados.
</div>
{% endif %}
{% endif %}

{% endblock %}

src/templates/movimientos/transferencia.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
    <div class="container mt-5">
        <h1 class="text-center mb-4">Realizar Transferencia</h1>
        
        {% bootstrap_messages %}
        
        <form method="post" action="{% url 'movimientos:transferencia' %}">
            {% csrf_token %}

            {% bootstrap_form form %}
                
            <button type="submit" class="btn btn-primary w-100">Transferir</button>
        </form>
    </div>
{% endblock %}

src/templates/movimientos/transferencia_cuenta.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
    <div class="container mt-5">
        <h1 class="text-center mb-4">Realizar Transferencia</h1>
        
        {% bootstrap_messages %}
        
        <form method="post" action="{% url 'movimientos:transferencia' %}">
            {% csrf_token %}

            {% bootstrap_form form %}
                
            <button type="submit" class="btn btn-primary w-100">Transferir</button>
        </form>
    </div>
{% endblock %}

src/templates/movimientos/ultimos_movimientos.html
    {% if movimientos %}
<div class="table-responsive">
    <table class="table table-striped table-hover table-bordered align-middle"> 
        <thead class="table-dark">
            <tr>
                <th class="text-center">Fecha</th>
                <th class="text-center">Tipo</th>
                <th class="text-center">Monto</th>
                <th class="text-center">Cuenta Vinculada</th>
                <th class="text-center">Motivo Transferencia</th>
            </tr>
        </thead>
        <tbody>
            {% for movimiento in movimientos %}
            <tr>
                <td class="text-center text-nowrap">{{ movimiento.fecha|date:"d/m/Y H:i" }}</td>
                <td>{{ movimiento.get_tipo_display }}</td>
                <td class="text-end {% if movimiento.get_tipo_display == 'Transferencia enviada' %}text-danger{% endif %}">
                    {% if movimiento.get_tipo_display == 'Transferencia enviada' %} - {% endif %}{{ movimiento.monto }}
                </td>
                <td class="text-center">
                    {% if movimiento.cuenta_asociada %}
                        {{ movimiento.cuenta_asociada.username }}
                    {% else %}
                        N/A
                    {% endif %}
                </td>
                <td class="text-center">
                    {% if movimiento.transferencia_motivo %}
                        {{ movimiento.transferencia_motivo }}
                    {% else %}
                        N/A
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p class="mb-0 fst-italic text-secondary fw-bold">Sin historial.</p>
    {% endif %}
</div>