src/apps/transferencia_motivo/urls.py
from django.urls import path
from .views import (
    MotivoListView,
    MotivoCreateView,
    MotivoUpdateView,
    MotivoDeleteView,
)

app_name = 'transferencia_motivo'

urlpatterns = [
    path('', MotivoListView.as_view(), name='list'),
    path('crear/', MotivoCreateView.as_view(), name='create'),
    path('<int:pk>/editar/', MotivoUpdateView.as_view(), name='update'),
    path('<int:pk>/eliminar/', MotivoDeleteView.as_view(), name='delete'),
]

src/apps/usuarios/urls.py
from django.urls import path

from .views import AdminUsuariosListView, AdminUsuariosUpdateView

app_name = 'usuarios'

urlpatterns = [
    path('', AdminUsuariosListView.as_view(), name="list"),
    path('<int:pk>/editar', AdminUsuariosUpdateView.as_view(), name="update"),
]

src/config/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

from . import views

# Vistas de apps.usuarios que quiero que tenga path desde de la raiz
from apps.usuarios import views as usuarios_views
from apps.movimientos import views as movimientos_views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('panel', usuarios_views.UsuarioPanelView.as_view(), name='panel'),
    path('perfil', usuarios_views.UsuarioUpdateProfileView.as_view(), name='profile'),
    path('registro', usuarios_views.UsuarioRegistroView.as_view(), name='register'),
    path('login', usuarios_views.UsuarioLoginView.as_view(), name='login'),
    path('logout', usuarios_views.UsuarioLogoutView.as_view(), name='logout'),
    # Reset password
    path('resetear-password/', usuarios_views.UsuarioResetearPasswordView.as_view(), name='password_reset'),
    path('resetear-password/done', usuarios_views.UsuarioResetearPasswordDoneView.as_view(), name='password_reset_done'),
    path('resetear-password/confirm/<uidb64>/<token>/', usuarios_views.UsuarioResetearPasswordConfirmView.as_view(), name='password_reset_confirm'),
    path('resetear-password/complete', usuarios_views.UsuarioResetearPasswordCompleteView.as_view(), name='password_reset_complete'),
    # Fin reset password
    path('cambiar-password/', usuarios_views.UsuarioCambiarPasswordView.as_view(), name='cambiar-password'),
    path('administracion/transferencia_motivo/', include('apps.transferencia_motivo.urls')),
    path('administracion/usuarios/', include('apps.usuarios.urls')),
    path("administracion/movimientos", movimientos_views.HistorialMovimientosAdmin.as_view(), name="admin_historial"),
    path('movimientos/', include('apps.movimientos.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/_filter_pagination.html
{% if page_obj.paginator.num_pages > 1 %}
<nav aria-label="Paginador">
  <ul class="pagination justify-content-center">
    <li class="page-item{% if not page_obj.has_previous %} disabled{% endif %}">
      {% if page_obj.has_previous %}
      <a class="page-link" href="{{ base_url|default:request.path }}{% querystring page=page_obj.previous_page_number %}">
        <i class="fa-solid fa-left-long"></i>
      </a>
      {% else %}
      <span class="page-link">
        <i class="fa-solid fa-left-long"></i>
      </span>
      {% endif %}
    </li>
{% for p in page_obj.paginator.page_range %}
  {% if p == page_obj.number %}
    <li class="page-item active" aria-current="page">
      <span class="page-link">{{ p }}</span>
    </li>
  {% else %}
    <li class="page-item">
      <a class="page-link" href="{{ base_url|default:request.path }}{% querystring page=p %}">{{ p }}</a>
    </li>
  {% endif %}
{% endfor %}
    <li class="page-item{% if not page_obj.has_next %} disabled{% endif %}">
      {% if page_obj.has_next %}
        <a class="page-link" href="{{ base_url|default:request.path }}{% querystring page=page_obj.next_page_number %}">
          <i class="fa-solid fa-right-long"></i>
        </a>
      {% else %}
        <span class="page-link">
          <i class="fa-solid fa-right-long"></i>
        </span>
      {% endif %}
    </li>
  </ul>
</nav>
{% endif %}

src/templates/_footer.html
<div class="bg-body-tertiary">
    <div class="container-xl text-center text-md-end py-4 fs-5 text-truncate fw-bold text-secondary">
       <i class="fa-solid fa-robot me-2"></i>
       <i class="fa-solid fa-terminal me-2"></i>
       ECOM Python Bootcamp - 2024
    </div>
</div>

src/templates/_navbar.html
{% load static %}
<nav class="navbar navbar-expand-md bg-body-tertiary">
  <div class="container-xl">
    <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static 'assets/images/logo.png' %}" alt="Logo Money Share">
        Money Share
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto align-items-md-center">
        {% if not user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'register' %}">
            <i class="fa-solid fa-user-plus me-2"></i>Registrate
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">
            <i class="fa-solid fa-arrow-right-to-bracket me-2"></i>Ingresar
          </a>
        </li>
        {% else %}
        {% if user.is_staff or user.is_superuser %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <div class="fa-solid fa-gear"></div> Administración
            </a>
            <ul class="dropdown-menu dropdown-menu-end">
              <li>
                  <a class="dropdown-item" href="{% url 'usuarios:list' %}">
                    <i class="fa-solid fa-users me-2"></i>Usuarios
                  </a>
              </li>
              <li>
                  <a class="dropdown-item" href="{% url 'admin_historial' %}">
                    <i class="fa-solid fa-right-left me-2"></i>Historial de movimientos
                  </a>
              </li>
              <li><hr class="dropdown-divider"></li>
              <li>
                  <a class="dropdown-item" href="{% url 'transferencia_motivo:list' %}">
                    <i class="fa-solid fa-right-left me-2"></i>Motivos de Transferencia
                  </a>
              </li>
            </ul>
        </li>  
        {% endif %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle d-flex flex-row align-items-center gap-2" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            {% if user.avatar %}
              <span class="avatar" style="background-image: url({{ user.avatar.url }})"></span>
            {% else %}
              <span class="avatar" style="background-image: url({% static 'assets/images/user.svg' %})"></span>
            {% endif %}
            {{ user.username }}
            {% if user.is_superuser %}
              (superuser)
            {% elif user.is_staff %}
              (staff)
            {% endif %}
            
          </a>
          <ul class="dropdown-menu dropdown-menu-end">
            <li>
                <a class="dropdown-item" href="{% url 'profile' %}">
                  <i class="fa-regular fa-id-card me-2"></i>Perfil
                </a>
            </li>
            <li>
                <a class="dropdown-item" href="{% url 'cambiar-password' %}">
                  <i class="fa-solid fa-lock-open me-2"></i>Cambiar contraseña
                </a>
            </li>
            <li><hr class="dropdown-divider"></li>
            <li>
                <form action="{% url 'logout' %}" method="post" class="d-grid">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-link text-start text-decoration-none text-reset px-3">
                    <i class="fa-solid fa-arrow-right-from-bracket me-2"></i>Salir
                  </button>
                </form>
            </li>
          </ul>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

src/templates/base.html
{% load static %}
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="es" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Money Share | {% block title %}{% endblock %}</title>
    <link rel="icon" type="image/png" href="{% static 'assets/images/logo.png' %}" />
    {% bootstrap_css %}
    <link href="{% static 'css/app.css' %}" rel="stylesheet" type="text/css">
    {% block page_css %}{% endblock %}
</head>
<body>
    <header>
        {% include '_navbar.html' %}
    </header>
    <main id="main" class="container-xl pt-3 pb-5">
    {% block content %}
        
    {% endblock %}
    </main>
    <footer>
        {% include '_footer.html' %}
    </footer>
    {% bootstrap_javascript %}
    <script defer src="{% static 'js/fontawesome/brands.min.js' %}"></script>
    <script defer src="{% static 'js/fontawesome/solid.min.js' %}"></script>
    <script defer src="{% static 'js/fontawesome/regular.min.js' %}"></script>
    <script defer src="{% static 'js/fontawesome/fontawesome.min.js' %}"></script>
    <script src="{% static 'js/app.js' %}"></script>
    {% block page_js %}{% endblock %}
</body>
</html>

src/templates/home.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="text-center fst-italic my-5 money-color">
       <i class="fa-solid fa-money-bill-transfer me-2"></i>"Envía y recibe dinero en segundos."
    </h1>
    <div class="d-flex flex-column flex-lg-row gap-5 align-items-md-center justify-content-md-center mb-5">
        <p class="fs-4 mb-0">
            "Con Money Share, transferir dinero es fácil, rápido y seguro.<br>
            Perfecto para tus necesidades personales y empresariales."
        </p>
        <a href="{% url 'register' %}" class="btn btn-primary btn-lg text-nowrap">
            <div class="fa-solid fa-user-plus me-2"></div><br>
            Regístrate
        </a>
    </div>
    <hr>
    <div class="d-flex align-items-center justify-content-center my-5 lead">
        <ul class="list-unstyled mb-0">
            <li><i class="fa-regular fa-circle-check me-3 fa-lg money-color"></i>Rápido: Transferencias instantáneas en cualquier momento.</li>
            <li><i class="fa-regular fa-circle-check me-3 fa-lg money-color"></i>Seguro: Protección de datos con cifrado de última generación.</li>
            <li><i class="fa-regular fa-circle-check me-3 fa-lg money-color"></i>Fácil de usar: Plataforma intuitiva para todos los niveles.</li>
            <li><i class="fa-regular fa-circle-check me-3 fa-lg money-color"></i>Transparente: Sin costos ocultos ni sorpresas desagradables.</li>
        </ul>
    </div>
    
    <div class="text-center fs-1 fst-italic">¡Gracias por elegir Money Share!</div>
{% endblock %}