src/apps/transferencia_motivo/urls.py
from django.urls import path
from .views import (
    MotivoListView,
    MotivoCreateView,
    MotivoUpdateView,
    MotivoDeleteView,
)

app_name = 'transferencia_motivo'

urlpatterns = [
    path('', MotivoListView.as_view(), name='list'),
    path('crear/', MotivoCreateView.as_view(), name='create'),
    path('<int:pk>/editar/', MotivoUpdateView.as_view(), name='update'),
    path('<int:pk>/eliminar/', MotivoDeleteView.as_view(), name='delete'),
]

src/config/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

from . import views

# Vistas de apps.usuarios que quiero que tenga path desde de la raiz
from apps.usuarios import views as usuarios_views
from apps.movimientos import views as movimientos_views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('panel', usuarios_views.UsuarioPanelView.as_view(), name='panel'),
    path('perfil', usuarios_views.UsuarioUpdateProfileView.as_view(), name='profile'),
    path('registro', usuarios_views.UsuarioRegistroView.as_view(), name='register'),
    path('login', usuarios_views.UsuarioLoginView.as_view(), name='login'),
    path('logout', usuarios_views.UsuarioLogoutView.as_view(), name='logout'),
    # Reset password
    path('resetear-password/', usuarios_views.UsuarioResetearPasswordView.as_view(), name='password_reset'),
    path('resetear-password/done', usuarios_views.UsuarioResetearPasswordDoneView.as_view(), name='password_reset_done'),
    path('resetear-password/confirm/<uidb64>/<token>/', usuarios_views.UsuarioResetearPasswordConfirmView.as_view(), name='password_reset_confirm'),
    path('resetear-password/complete', usuarios_views.UsuarioResetearPasswordCompleteView.as_view(), name='password_reset_complete'),
    # Fin reset password
    path('cambiar-password/', usuarios_views.UsuarioCambiarPasswordView.as_view(), name='cambiar-password'),
    path('administracion/transferencia_motivo/', include('apps.transferencia_motivo.urls')),
    path('administracion/usuarios/', include('apps.usuarios.urls')),
    path("administracion/movimientos", movimientos_views.HistorialMovimientosAdmin.as_view(), name="admin_historial"),
    path('movimientos/', include('apps.movimientos.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/apps/transferencia_motivo/models.py
from django.db import models

class MotivoTransferencia(models.Model):
    descripcion = models.CharField(max_length=100, verbose_name='Descripción')

    def __str__(self):
        return self.descripcion
        
    

src/apps/transferencia_motivo/forms.py
# forms.py
from django import forms
from .models import MotivoTransferencia

class MotivoTransferenciaForm(forms.ModelForm):
    class Meta:
        model = MotivoTransferencia
        fields = ['descripcion']  # Incluye los campos del modelo que quieras mostrar


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Agrega la un place holder al input
        self.fields['descripcion'].widget.attrs.update({
            'placeholder': 'Escribe el motivo aquí...'  # Ejemplo de un atributo adicional
        })

src/apps/transferencia_motivo/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .models import MotivoTransferencia
from .forms import MotivoTransferenciaForm
from django.contrib.messages.views import SuccessMessageMixin
from config.mixins import TestStaffMixin

class MotivoListView(TestStaffMixin, ListView):
    model = MotivoTransferencia
    template_name = 'transferencia_motivo/motivo_list.html'
    context_object_name = 'motivos'

class MotivoCreateView(TestStaffMixin,SuccessMessageMixin, CreateView):
    model = MotivoTransferencia
    form_class = MotivoTransferenciaForm
    template_name = 'transferencia_motivo/motivo_form.html'
    success_url = reverse_lazy('transferencia_motivo:list')
    success_message = "Guardado con éxito."

class MotivoUpdateView(TestStaffMixin, SuccessMessageMixin, UpdateView):
    model = MotivoTransferencia
    fields = ['descripcion']
    template_name = 'transferencia_motivo/motivo_form.html'
    success_url = reverse_lazy('transferencia_motivo:list')
    success_message = "Guardado con éxito."

class MotivoDeleteView(TestStaffMixin,SuccessMessageMixin, DeleteView):
    model = MotivoTransferencia
    template_name = 'transferencia_motivo/motivo_confirm_delete.html'
    success_url = reverse_lazy('transferencia_motivo:list')
    success_message = "Borrado con éxito."

src/transferencia_motivo/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .models import MotivoTransferencia

class MotivoListView(ListView):
    model = MotivoTransferencia
    template_name = 'transferencia_motivo/motivo_list.html'
    context_object_name = 'motivos'

class MotivoCreateView(CreateView):
    model = MotivoTransferencia
    fields = ['descripcion']
    template_name = 'transferencia_motivo/motivo_form.html'
    success_url = reverse_lazy('transferencia_motivo:list')

class MotivoUpdateView(UpdateView):
    model = MotivoTransferencia
    fields = ['descripcion']
    template_name = 'transferencia_motivo/motivo_form.html'
    success_url = reverse_lazy('transferencia_motivo:list')

class MotivoDeleteView(DeleteView):
    model = MotivoTransferencia
    template_name = 'transferencia_motivo/motivo_confirm_delete.html'
    success_url = reverse_lazy('transferencia_motivo:list')

src/templates/transferencia_motivo/motivo_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<h1>Eliminar Motivo</h1>
<div class="border border-secondary rounded p-3">
    <p>¿Estás seguro de que quieres eliminar "{{ object }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button class="btn btn-danger" type="submit">Sí, eliminar</button>
        <a class="btn btn-secondary" href="{% url 'transferencia_motivo:list' %}">Cancelar</a>
    </form>
</div>
{% endblock %}

src/templates/transferencia_motivo/motivo_form.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
<h1>{% if object %}Editar Motivo{% else %}Crear Motivo{% endif %}</h1>
<form method="post" class="border border-secondary rounded p-3">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% bootstrap_button button_type="submit" content="Guardar" button_class="btn-primary me-2" %}
    {% url 'transferencia_motivo:list' as cancelar_link %}
    {% bootstrap_button button_type="link" button_class="btn-secondary" href=cancelar_link content="Cancelar" %}
</form>
{% endblock %}

src/templates/transferencia_motivo/motivo_list.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
<h1 class="text-truncate">Lista de Motivos de Transferencia</h1>
{% bootstrap_messages %}
<a class ="btn btn-primary mb-3" href="{% url 'transferencia_motivo:create' %}">Nuevo Motivo</a>
<ul class="list-group">
    {% for motivo in motivos %}
    <li class="list-group-item d-flex flex-row align-items-center">
        <div class="flex-fill text-truncate">
            {{ motivo.descripcion }} 
        </div> 
        <ul class="list-unstyled d-flex flex-row gap-1">
            <li>
                <a class="btn btn-link text-decoration-none" href="{% url 'transferencia_motivo:update' motivo.id %}">
                    <i class="fa-solid fa-pen fa-lg"></i>
                    <span class="visually-hidden">editar {{ motivo.descripcion }}</span>
                </a>
            </li>
            <li>
                <a class="btn btn-link text-decoration-none" href="{% url 'transferencia_motivo:delete' motivo.id %}">
                    <div class="fa-regular fa-trash-can fa-lg"></div>
                    <span class="visually-hidden">eliminar {{ motivo.descripcion }}</span>
                </a>
            </li>
        </ul>
    </li>
    {% endfor %}
</ul>
{% endblock %}