src/apps/movimientos/urls.py
from django.urls import path
from .views import (
   Transferencia,
   HistorialMovimientos,
   IngresoDinero,
   TransferenciaCuenta,
   MovimientoDetailView,
   # HistorialMovimientosAdmin
)

app_name = "movimientos"

urlpatterns = [
    path("historial/", HistorialMovimientos.as_view(), name="historial"),
    path('transferencia/', Transferencia.as_view(), name='transferencia'),
    path("ingreso_dinero/", IngresoDinero.as_view(), name="ingreso_dinero"),
    path('transferencia_cuenta/<int:cuenta_asociada_id>/', TransferenciaCuenta.as_view(), name='transferencia_cuenta'),
    path('movimiento_detail/<int:pk>/', MovimientoDetailView.as_view(), name='movimiento_detail'),
    # path("admin_historial/", HistorialMovimientosAdmin.as_view(), name="admin_historial"),
]

src/apps/usuarios/urls.py
from django.urls import path

from .views import AdminUsuariosListView, AdminUsuariosUpdateView

app_name = 'usuarios'

urlpatterns = [
    path('', AdminUsuariosListView.as_view(), name="list"),
    path('<int:pk>/editar', AdminUsuariosUpdateView.as_view(), name="update"),
]

src/config/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

from . import views

# Vistas de apps.usuarios que quiero que tenga path desde de la raiz
from apps.usuarios import views as usuarios_views
from apps.movimientos import views as movimientos_views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('panel', usuarios_views.UsuarioPanelView.as_view(), name='panel'),
    path('perfil', usuarios_views.UsuarioUpdateProfileView.as_view(), name='profile'),
    path('registro', usuarios_views.UsuarioRegistroView.as_view(), name='register'),
    path('login', usuarios_views.UsuarioLoginView.as_view(), name='login'),
    path('logout', usuarios_views.UsuarioLogoutView.as_view(), name='logout'),
    # Reset password
    path('resetear-password/', usuarios_views.UsuarioResetearPasswordView.as_view(), name='password_reset'),
    path('resetear-password/done', usuarios_views.UsuarioResetearPasswordDoneView.as_view(), name='password_reset_done'),
    path('resetear-password/confirm/<uidb64>/<token>/', usuarios_views.UsuarioResetearPasswordConfirmView.as_view(), name='password_reset_confirm'),
    path('resetear-password/complete', usuarios_views.UsuarioResetearPasswordCompleteView.as_view(), name='password_reset_complete'),
    # Fin reset password
    path('cambiar-password/', usuarios_views.UsuarioCambiarPasswordView.as_view(), name='cambiar-password'),
    path('administracion/transferencia_motivo/', include('apps.transferencia_motivo.urls')),
    path('administracion/usuarios/', include('apps.usuarios.urls')),
    path("administracion/movimientos", movimientos_views.HistorialMovimientosAdmin.as_view(), name="admin_historial"),
    path('movimientos/', include('apps.movimientos.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/apps/usuarios/models.py
from django.db import models
import os

from django.contrib.auth.models import AbstractUser

# Create your models here.

class Usuario(AbstractUser):
    saldo = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    avatar = models.ImageField(upload_to='usuarios/', verbose_name='Avatar', null=True, blank=True)

    # _original_avatar se utiliza con signals para eliminar el archivo si se cambia o elimina
    __original_avatar = None

src/apps/usuarios/forms.py
from .models import Usuario

from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class UsuarioForm(UserCreationForm):
    class Meta:
        model = Usuario
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']

class UsuarioUpdateForm(UserChangeForm):
    class Meta:
        model = Usuario
        fields = ['email', 'first_name', 'last_name', 'avatar']

class AdminUsuarioUpdateForm(UserChangeForm):
    class Meta:
        model = Usuario
        fields = ['is_active', 'email', 'first_name', 'last_name', 'avatar', 'is_staff']

src/apps/usuarios/views.py
from django.db.models.base import Model as Model
from django.db.models.query import QuerySet
from django.http.response import HttpResponse as HttpResponse
from django.shortcuts import redirect
from .forms import UsuarioForm, UsuarioUpdateForm, AdminUsuarioUpdateForm
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView, UpdateView

from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView
from django.contrib.auth.views import PasswordResetConfirmView, PasswordResetCompleteView 

from django.contrib.auth.decorators import login_not_required
from django.utils.decorators import method_decorator
from apps.movimientos.models import Movimiento
from django.contrib.messages.views import SuccessMessageMixin

from django_filters.views import FilterView

from .models import Usuario
from config.mixins import TestStaffMixin

# Create your views here.

@method_decorator(login_not_required, name='dispatch')
class UsuarioRegistroView(CreateView):
    form_class = UsuarioForm
    success_url = reverse_lazy("login")
    template_name = 'usuarios/registro.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('panel')
        return super(UsuarioRegistroView, self).dispatch(request, *args, **kwargs)
    
class UsuarioLoginView(LoginView):
    redirect_authenticated_user = True
    template_name = 'usuarios/login.html'

###### Resetear password
class UsuarioResetearPasswordView(PasswordResetView):
    template_name = 'usuarios/resetear_password/form.html'
    html_email_template_name = 'usuarios/resetear_password/email.html'
    subject_template_name = 'usuarios/resetear_password/subject.txt'
    success_url = reverse_lazy('password_reset_done')

class UsuarioResetearPasswordDoneView(PasswordResetDoneView):
    template_name = 'usuarios/resetear_password/done.html'

class UsuarioResetearPasswordConfirmView(SuccessMessageMixin, PasswordResetConfirmView):
    template_name = 'usuarios/resetear_password/confirm.html'
    success_url = reverse_lazy('panel')
    post_reset_login = True
    success_message = "Tu contraseña ha sido cambiada con exito."

class UsuarioResetearPasswordCompleteView(PasswordResetCompleteView):
    template_name = 'usuarios/resetear_password/complete.html'

# Fin resetear password

class UsuarioLogoutView(LogoutView):
    next_page = reverse_lazy('home')

class UsuarioPanelView(TemplateView):
    template_name = 'usuarios/panel.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['movimientos'] = Movimiento.objects.filter(cuenta=self.request.user.id).order_by("-fecha")[:5]
        limite = int(self.request.GET.get('limite', 10))  # Valor dinámico de límite
        context['cuentas'] = Movimiento.objects.cuentas_mas_utilizadas(usuario=self.request.user.id, limite=limite)
        return context

class UsuarioUpdateProfileView(UpdateView):
    form_class = UsuarioUpdateForm
    success_url = reverse_lazy("panel")
    template_name = 'usuarios/perfil.html'

    def get_object(self, queryset: QuerySet[any] | None = ...) -> Model:
        return self.request.user
    
class UsuarioCambiarPasswordView(SuccessMessageMixin, PasswordChangeView):
    template_name = 'usuarios/cambiar_password.html'
    success_url = reverse_lazy("panel")
    success_message = "Contraseña cambiada con exito."

# Administracion de usuarios views
class AdminUsuariosListView(TestStaffMixin, FilterView):
    filterset_fields = {
        'username': ['icontains'],
        'is_staff': ['exact'],
    }
    model = Usuario
    paginate_by = 10
    template_name = 'usuarios/admin_list.html'

class AdminUsuariosUpdateView(SuccessMessageMixin, TestStaffMixin, UpdateView):
    model = Usuario
    form_class = AdminUsuarioUpdateForm
    success_url = reverse_lazy("usuarios:list")
    success_message = "Datos del usuario actualizados con exito."
    template_name = 'usuarios/admin_update.html'

    def get_form(self, form_class=None):
        form = super(AdminUsuariosUpdateView, self).get_form(form_class)
        o = form.instance
        if not self.request.user.is_superuser and o.is_superuser:
            # Deshabilitar campos de superusuario
            fields = ['email', 'is_active', 'is_staff']
            for f in fields:
                form.fields[f].disabled = True
        return form

    def get_success_url(self) -> str:
        o = self.object
        if (o.id == self.request.user.id) and not (o.is_staff or o.is_superuser):
            self.success_url = reverse_lazy('panel')
        return super().get_success_url()

src/templates/usuarios/admin_list.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block title %}Usuarios{% endblock %}
{% block content %}
    <h1><i class="fa-solid fa-users fa-xs me-2"></i>Usuarios</h1>
    {{ querystring }}
    <form method="get" class="filter-form border border-secondary rounded p-3 mb-3 bg-body-tertiary">
        <div class="row">
            <div class="col-md-6">{% bootstrap_field filter.form.username__icontains %}</div>
            <div class="col-md-6">{% bootstrap_field filter.form.is_staff %}</div>
        </div>
        <ul class="list-inline mb-0 text-end">
            <li class="list-inline-item"><button class="btn btn-primary" type="submit">Buscar</button></li>
            <li class="list-inline-item"><button class="btn btn-secondary" type="reset">Limpiar</button></li>
        </ul>
    </form>
    {% bootstrap_messages %}
    <div class="mb-3 fw-bold">
    {{ page_obj.paginator.count }} registro{% if page_obj.paginator.count != 1 %}s{% endif %}.
    </div>
    <div class="table-responsive">
        <table class="table table-hover table-striped align-middle caption-top">
            <caption class="visually-hidden">Listado de usuarios</caption>
            <thead>
                <tr class="table-secondary">
                    <th scope="col">Usuario</th>
                    <th scope="col" class="text-nowrap">Nombre y Apellido</th>
                    <th scope="col">Email</th>
                    <th scope="col" class="text-center text-nowrap">Es staff</th>
                    <th scope="col" class="text-center">Acciones</th>
                </tr>
            </thead>
            <tbody>
            {% for usuario in object_list %}
                <tr>
                    <td>{{ usuario.username }}</td>
                    <td>{{ usuario.get_full_name }}</td>
                    <td>{{ usuario.email }}</td>
                    <td class="text-center">{% if usuario.is_staff %}SI{% else %}NO{% endif %}</td>
                    <td>
                        <a class="btn btn-link text-decoration-none" href="{% url 'usuarios:update' usuario.id %}">
                            <i class="fa-solid fa-pen fa-lg"></i>
                        </a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    {% include '_filter_pagination.html' %}
{% endblock %}

src/templates/usuarios/admin_update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block title %}Editar Usuario{% endblock %}

{% block content %}
<h1><i class="fa-solid fa-user-pen fa-xs me-2"></i>Editar al usuario: {{ object }}</h1>
{% bootstrap_messages %}
<form method="post" enctype="multipart/form-data" class="border border-secondary rounded p-3">
  {% csrf_token %}
  {% bootstrap_field form.is_active %}
  {% bootstrap_field form.email %}
  <div class="row">
    <div class="col-lg-6">{% bootstrap_field form.first_name %}</div>
    <div class="col-lg-6">{% bootstrap_field form.last_name %}</div>
  </div>
  {% bootstrap_field form.avatar %}
  {% bootstrap_field form.is_staff %}
  <div class="text-end">
    {% bootstrap_button button_type="submit" content="Guardar" %}
  </div>
</form>
{% endblock %}

src/templates/usuarios/cambiar_password.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block title %}Cambiar Contraseña{% endblock %}

{% block content %}
<h1><i class="fa-solid fa-lock-open fa-xs me-2"></i>Cambiar contraseña</h1>
{% bootstrap_messages %}
<form method="post" class="cambiar-contrasenia-form border border-secondary rounded p-3">
  {% csrf_token %}
  {% bootstrap_form form %}
  <div class="text-end">
    {% bootstrap_button button_type="submit" content="Cambiar" %}
  </div>
</form>
{% endblock %}

src/templates/usuarios/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block title %}Ingreso{% endblock %}

{% block content %}
<h1><i class="fa-solid fa-arrow-right-to-bracket fa-xs me-2"></i>Ingreso</h1>
{% bootstrap_messages %}
<form method="post" class="border border-secondary rounded p-3" id="login-form">
  {% csrf_token %}
  {% bootstrap_form form %}
  <div class="text-end">
    {% bootstrap_button button_type="submit" content="Ingresar" %}
  </div>
  <hr>
  <div class="fw-bold">
    <a class="text-decoration-none" href="{% url 'password_reset' %}">¿Has olvidado tu contraseña? <i class="fa-solid fa-lock-open"></i></a>
  </div>
</form>

{% endblock %}

src/templates/usuarios/panel.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}Panel{% endblock %}
{% block content %}
    <h1 class="h2"><i class="fa-regular fa-user fa-xs me-2"></i>Benvenido <span class="text-info">{{ user.username }}</span>!!!</h1>
    {% bootstrap_messages %}
    <section class="d-flex flex-column flex-md-row gap-4 align-items-center justify-content-center p-3 mb-3 fs-2">
        <div class="d-inline-block bg-body-tertiary py-3 px-4 rounded-3">
            <span class="visually-hidden">Su saldo:</span>
            <i class="fa-solid fa-sack-dollar me-1 text-warning"></i>
            <i class="fa-solid fa-dollar-sign me-2"></i>{{ user.saldo }}
        </div>
        <ul class="list-inline d-flex flex-row gap-2 mb-0">
            <li class="list-inline-item">
                <a href="{% url 'movimientos:ingreso_dinero' %}" class="btn btn-success border-2" data-bs-toggle="tooltip" data-bs-title="Ingrese dinero">
                    <i class="fa-solid fa-plus fa-lg"></i>
                </a>
            </li>
            <li class="list-inline-item">
                <a href="{% url 'movimientos:transferencia' %}" class="btn btn-success primary border-2" data-bs-toggle="tooltip" data-bs-title="Envíe dinero">
                    <i class="fa-solid fa-money-bill-transfer fa-lg"></i>
                </a>
            </li>
        </ul>
    </section>
    <section id="favoritos" class="mb-4">
        <h2 class="h3"><i class="fa-regular fa-star fa-xs me-2"></i>Favoritos</h2>
        <div class="px-3">
            {% include 'movimientos/cuentas_favoritas.html' %}
        </div>
    </section>
    <section id="historial">
        <h2 class="h3"><i class="fa-regular fa-file-lines fa-xs me-2"></i>Historial</h2>
        <div class="px-3">
            {% include 'movimientos/ultimos_movimientos.html' %}
            <div class="text-end">
                <a href="{% url 'movimientos:historial' %}" class="fw-bold text-decoration-none">Ver todo ...</a>
            </div>
        </div>
    </section>
{% endblock %}

src/templates/usuarios/perfil.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block title %}Mi Perfil{% endblock %}

{% block content %}
<h1><i class="fa-solid fa-user-pen fa-xs me-2"></i>Mi Perfil</h1>
{% bootstrap_messages %}
<form method="post" enctype="multipart/form-data" class="border border-secondary rounded p-3">
  {% csrf_token %}
  {% bootstrap_field form.username %}
  {% bootstrap_field form.email %}
  <div class="row">
    <div class="col-lg-6">{% bootstrap_field form.first_name %}</div>
    <div class="col-lg-6">{% bootstrap_field form.last_name %}</div>
  </div>
  {% bootstrap_field form.avatar %}
  <div class="text-end">
    {% bootstrap_button button_type="submit" content="Guardar" %}
  </div>
</form>
{% endblock %}

src/templates/usuarios/registro.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block title %}Registro de usuario{% endblock %}

{% block content %}
<h1><i class="fa-solid fa-user-plus fa-xs me-2"></i>Registro</h1>
{% bootstrap_messages %}
<form method="post" class="border border-secondary rounded p-3">
  {% csrf_token %}
  {% bootstrap_field form.username %}
  {% bootstrap_field form.email %}
  <div class="row">
    <div class="col-lg-6">{% bootstrap_field form.first_name %}</div>
    <div class="col-lg-6">{% bootstrap_field form.last_name %}</div>
  </div>
  <div class="bg-body-tertiary p-3 mb-3 rounded">
    <div class="row">
      <div class="col-lg-6">{% bootstrap_field form.password1 %}</div>
      <div class="col-lg-6">{% bootstrap_field form.password2 %}</div>
    </div>
  </div>
  <div class="text-end">
    {% bootstrap_button button_type="submit" content="Registrarme" %}
  </div>
</form>
{% endblock %}